### PR TITLE
initialize app with yeomann webapp and bower.

### PR DESCRIPTION
**Pull request by courtneyportnoy**
Hi Matt. I was able to get Yeoman working and created a basic app to get started.

### CODE REVIEW

**Comment by matstc** [comment]
Looks good Courtney. Are you able to use coffee script with the current setup?

**Comment by courtneyportnoy** [comment]
Hi Matt. I haven't figured out how to use coffeescript with this yet. Coffeescript is included but if I create a .coffee file it doesn't seem to auto-compile. I'm also getting an error within the coffeescript file itself. See image attached. 
screen shot 2015-04-17 at 5 49 15 pm

**Comment by matstc** [comment]
All right, that makes sense. I'll have a look now and hopefully commit a fix.

**Comment by matstc** [comment]
Done. Let me know if that works for you. All you should have to do is add `.coffee` files under `scripts` and make sure they are included in the HTML.

**Comment by courtneyportnoy** [comment]
Works for me now. Thanks!

**Comment by courtneyportnoy** [comment]
Matt - the latest commit (separate JS files) results in errors. The main.coffee file is not able to see the player, paddle, ball classes. Am I missing a step? All the coffee files are included in the index.html file.

**Comment by matstc** [comment]
Hi Courtney—

I fixed three things:
- I changed the configuration of the `wiredep` plugin so that all the JS
  files are automatically added to `index.html`.
- I declared all your classes onto `window` so that you can have access to
  them from anywhere in your code.
- I used your classes only from within the `onload` handler so you can be
  sure that your files have been loaded.

If this works well for you, feel free to merge or rebase the `develop`
branch into master. There's no point in avoiding master.

**Pull request merged**
